[colors.bright]
black = "#7a7b70"
blue = "#83a598"
cyan = "#8ec87c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fffffa"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#101010"
foreground = "#d7d3b4"

[font]
size = 9.1

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "SemiBold"

[window.padding]
x = 0 
y = 5 

[cursor]
style = { shape = "Beam" }
